### ISSUE TITLE
It's getting a bit hard for multilingual at this moment

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-platform#666] opened 2016-11-18 14:24 UTC
We have a few different type of product properties
1. We have a date time picker in multilingual, but it only show one date time picker over there.
2. We have a checkbox in multilingual, but it only show on checkbox over there also.
3. We have a dropdown in multilingual, but it only show on checkbox over there also.
4. We have a textbox in multilingual, but when we save the properties we got 500, only when we fill in all texts for all languages it does work   
![fill in property](https://cloud.githubusercontent.com/assets/4378651/20432999/0bc1ea7e-ada2-11e6-9c70-fb924b032315.png)

**Comment by tatarincev** [comment] 2016-11-18 14:28
Very bad issue number :)

**Comment by tatarincev** [comment] 2016-11-21 07:27
For DateTime and Bool property types Multilingual does not make sense, it is our UX bug.
For dictionary multilingual - when you choose value for this property,  you will select only one value for nominal language, other localized values just not displayed in UI for space economy,  
With 500 error when saving empty property values It looks as bug and we will check it.

**Comment by eMazeika** [comment] 2017-06-12 13:34
Closing the ticket as I couldn't reproduce the 500 error in the latest catalog module (ver. 2.16.7).
Feel free to reopen if error occurs again.

**Closed by eMazeika** 2017-06-12 13:34 UTC
