### ISSUE TITLE
When old modules exist platform fails to start with cryptic error 

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1804] opened 2020-03-19 06:58 UTC
**Describe the bug**
Platform fails to start

**Steps to reproduce**
1. Setup latest platform version from source
2. Download older module release, example Notification module rc1
3. Launch platform

**Expected behavior**
Want to see some error telling me I have an incompatible module, or better yet system should ignore incompatible module and show error under modules.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1566470/77039848-02a96480-6974-11ea-86e4-f0c8de1ce246.png)

**Version info (please complete the following information):**
 - Browser version:
 - Platform version: 3.0.0-rc.4.195+Branch.release-3.0.0.Sha.231f0eee4f7c9fc59b7ea199579c7a8ef3907b11

**Comment by akak1977** [comment] 2020-03-20 13:49
This is an RC version. In RC version every dependency set to 3.0.0 to simplify development and delivery.
Therefore it is strongly recommended to install modules with the same version tag as the platform.
As we release GA version there will be ordinal dependency resolving.

**Comment by lnetrebskii** [comment] 2020-06-15 14:39
The problem is obsolete. The ordinary versioning process is happening now.

**Closed by lnetrebskii** 2020-06-15 14:39 UTC
Labels: v3
