### ISSUE TITLE
System.IO.IOException: The process cannot access the file 'VirtoCommerce.Orders_3.1.0.zip' because it is being used by another process. 

### ISSUE THREAD

**Issue by shahidul56** [VirtoCommerce/vc-platform#1889] opened 2020-05-27 13:05 UTC
**Describe the bug**
module download takes much time for VirtoCommerce.Orders_3.1.0.zip then shows 

> System.IO.IOException: The process cannot access the file 'VirtoCommerce.Orders_3.1.0.zip' because it is being used by another process. 

**Steps to reproduce**
1. cd src\VirtoCommerce.Platform.Web
2. dotnet run -c Development --no-launch-profile

**Screenshots (optional)**
![dwdwd](https://user-images.githubusercontent.com/11449967/83019334-966c7080-a048-11ea-8eec-9cbd3be20682.PNG)

**Version info (please complete the following information):**
 - Browser version: chrome 81
 - Platform version: windows dotnetcore 3.0.1

**Comment by lnetrebskii** [comment] 2020-05-27 13:09
Task https://virtocommerce.atlassian.net/browse/VP-2614 has been created

**Comment by eMazeika** [comment] 2020-06-12 13:38
@shahidul56, sorry for the late reply. And one more sorry, because I couldn't reproduce the error. Could you repeat your scenario as there were many changes during last couple of weeks. Check this, VirtoCommerce.Orders **3.3.0** was auto-installed on my machine:

![image](https://user-images.githubusercontent.com/5801549/84508339-cf544880-acca-11ea-8966-256935463d25.png)

**Comment by OlegoO** [comment] 2021-05-14 08:45
Fixed in https://github.com/VirtoCommerce/vc-platform/releases/tag/3.54.0

**Closed by OlegoO** 2021-05-14 08:45 UTC
