### ISSUE TITLE
Platform - 404  response for some content requests on release version

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1026] opened 2017-07-11 12:38 UTC
http://localhost/platform/Content/themes/main/fonts/Exo-2-600/Exo-2-600.woff2

**Comment by asvishnyakov** [comment] 2017-07-11 13:28
Web.config transformed wrong. Caused by errors on build. See #1024

**Comment by asvishnyakov** [comment] 2017-07-11 15:28
Already fixed in dev

**Closed** 2017-07-17 20:24 UTC
