### ISSUE TITLE
Error while editing Dynamic property

### ISSUE THREAD

**Issue by priboltik** [VirtoCommerce/vc-platform#1469] opened 2018-11-12 09:22 UTC
I got error, when try to change the "Property name" field for Dynamic property.

1. Go to 'Dynamic properties'.
2. Click on any dynamic property for editing it.
3. Change the field "Property name".
4. Click 'Save'.
5. See error

Dynamic property should change the name, but...

**Screenshots (optional)**
![default](https://user-images.githubusercontent.com/1209682/48337845-e3b30800-e685-11e8-8969-87f492ca34d8.png)

 - Browser version: Google Chrome 70.0.3538.77
 - Platform version: 2.13.37

**Comment by eMazeika** [comment] 2018-11-30 10:53
duplicate of #1345 #1393

**Closed by eMazeika** 2018-11-30 10:53 UTC
Labels: duplicate
